### ISSUE TITLE
网易云本体为浅色时，收藏到歌单菜单文字和背景颜色一致。

### ISSUE THREAD

**Issue by PeterAlbus** [solstice23/refined-now-playing-netease#58]
![image](https://user-images.githubusercontent.com/57245496/216773788-7b3772d2-e3a3-48e2-879a-c764b0c62346.png)
如图所示，网易云菜单为浅色时会出现这种情况。（影响范围包括：收藏到歌单，和该处的新建歌单页面）
作为临时解决方案和参考，我添加了如下css来解决该问题。当然，该css没有考虑深色模式的情况，也没有去管新建歌单页面。
如果作者有空闲，非常感谢能想办法解决一下这个问题。当然，如果不方便解决，使用浅色模式的朋友们可以自行clone源码，在style.scss末尾添加这些并重新打包成插件，可以临时解决该问题。
```scss
.m-layer {
	color: black!important;
	.zbar {
		.zttl {
			color: rgba(0, 0, 0, 0.8)!important;
		}
	}
	.u-icn-laycls {
		svg {
			fill: rgba(0, 0, 0, 0.4)!important;
		}
		svg:hover {
			fill: rgba(0, 0, 0, 0.6)!important;
		}
	}
	.s-fc3 {
		color: rgba(0, 0, 0, 0.45)!important;
	}
}
```
